import { relations } from "drizzle-orm";
import {
	boolean,
	integer,
	jsonb,
	pgSchema,
	real,
	text,
	timestamp,
} from "drizzle-orm/pg-core";

// Use the 'shorty' schema
export const shortySchema = pgSchema("shorty");

// ============================================================================
// Enums
// ============================================================================

export const storyTypeEnum = shortySchema.enum("story_type", [
	"aistory",
	"podcast42",
	"director-mode",
]);

export const mediaStatusEnum = shortySchema.enum("media_status", [
	"ready",
	"generating",
	"completed",
]);

export const imageTypeEnum = shortySchema.enum("image_type", [
	"scene",
	"character",
	"person1",
	"person2",
]);

// ============================================================================
// Stories Table
// ============================================================================

export const stories = shortySchema.table("stories", {
	id: text("id").primaryKey(),
	ownerId: text("owner_id").notNull().default("anonymous"),
	type: storyTypeEnum("type").notNull(),

	// Story title (generated by LLM)
	title: text("title"),

	// Timestamps
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),

	// Input scripts
	script: text("script"),
	playScript: text("play_script"),

	// Engine settings
	imageEngine: text("image_engine").notNull(),
	imageStyle: text("image_style").notNull(),
	voiceId: text("voice_id"),
	person1VoiceId: text("person1_voice_id"),
	person2VoiceId: text("person2_voice_id"),
	videoEngine: text("video_engine"),
	podcast42VideoEngine: text("podcast42_video_engine"),

	// Character prompts (text prompts only)
	characterPrompt: text("character_prompt"),
	person1Prompt: text("person1_prompt"),
	person2Prompt: text("person2_prompt"),

	// Character image IDs (references to images table)
	// For aistory: person1ImageId stores the character image
	// For podcast42: person1ImageId and person2ImageId store both character images
	person1ImageId: text("person1_image_id"),
	person2ImageId: text("person2_image_id"),

	// Export status
	hasExportedVideo: boolean("has_exported_video").default(false),
	exportVideoUrl: text("export_video_url"), // Supabase Storage URL for exported video
	exportedVideoId: text("exported_video_id"), // Reference to videos table for exported video

	// Director Assistant conversation history (for director-mode stories)
	conversationHistory: jsonb("conversation_history").$type<
		Array<{
			id: string;
			role: "user" | "assistant";
			content: string;
			toolResults?: Array<{
				name: string;
				arguments: Record<string, unknown>;
				result: unknown;
			}>;
			timestamp: number;
		}>
	>(),
});

// ============================================================================
// Audios Table
// ============================================================================

export const audios = shortySchema.table("audios", {
	id: text("id").primaryKey(),
	ownerId: text("owner_id").notNull().default("anonymous"),
	storyId: text("story_id").references(() => stories.id, {
		onDelete: "set null",
	}),
	sceneId: text("scene_id"), // Nullable for orphaned media

	voiceId: text("voice_id").notNull(),
	prompt: text("prompt").notNull(), // The text/caption to generate

	audioUrl: text("audio_url"), // Supabase Storage URL

	status: mediaStatusEnum("status").notNull().default("ready"),

	// Audio-specific metadata
	duration: real("duration"),
	wordTimestamps: text("word_timestamps"), // JSON string

	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
});

// ============================================================================
// Images Table
// ============================================================================

export const images = shortySchema.table("images", {
	id: text("id").primaryKey(),
	ownerId: text("owner_id").notNull().default("anonymous"),
	storyId: text("story_id").references(() => stories.id, {
		onDelete: "set null",
	}),
	sceneId: text("scene_id"), // Nullable for character images or orphaned media

	prompt: text("prompt").notNull(),
	referenceImageId: text("reference_image_id"), // FK to another image for consistency

	imageUrl: text("image_url"), // Supabase Storage URL

	status: mediaStatusEnum("status").notNull().default("ready"),

	// Image type marker for character vs scene images
	imageType: imageTypeEnum("image_type").notNull().default("scene"),

	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
});

// ============================================================================
// Videos Table
// ============================================================================

export const videos = shortySchema.table("videos", {
	id: text("id").primaryKey(),
	ownerId: text("owner_id").notNull().default("anonymous"),
	storyId: text("story_id").references(() => stories.id, {
		onDelete: "set null",
	}),
	sceneId: text("scene_id"), // Nullable for orphaned media

	imageId: text("image_id").references(() => images.id), // Source image
	audioId: text("audio_id").references(() => audios.id), // Audio for sync

	prompt: text("prompt").notNull(),
	videoUrl: text("video_url"), // Supabase Storage URL

	status: mediaStatusEnum("status").notNull().default("ready"),

	// Video-specific metadata
	duration: real("duration"),

	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
});

// ============================================================================
// Scenes Table
// ============================================================================

export const scenes = shortySchema.table("scenes", {
	id: text("id").primaryKey(),
	ownerId: text("owner_id").notNull().default("anonymous"),
	storyId: text("story_id")
		.notNull()
		.references(() => stories.id, { onDelete: "cascade" }),
	orderIndex: integer("order_index").notNull(),

	// Content metadata
	caption: text("caption").notNull(),
	title: text("title"),
	prompt: text("prompt"),
	videoPrompt: text("video_prompt"),
	isCharacter: boolean("is_character"),
	speaker: text("speaker"), // "person1" | "person2" for podcast42

	// Per-scene voice settings
	voiceId: text("voice_id"),
	voiceSpeed: real("voice_speed").default(1.0),

	// Per-scene engine settings (for director-mode)
	imageEngine: text("image_engine"), // "flux-pro" | "gpt-image-1.5" | "nano-banana-pro"
	videoEngine: text("video_engine"), // "kling-video" | "sora-2" | "veo3.1" etc
	avatarEngine: text("avatar_engine"), // "omnihuman" | "aurora" (optional)

	// Foreign keys to media tables (nullable, 1:1 at scene level)
	imageId: text("image_id").references(() => images.id, {
		onDelete: "set null",
	}),
	audioId: text("audio_id").references(() => audios.id, {
		onDelete: "set null",
	}),
	videoId: text("video_id").references(() => videos.id, {
		onDelete: "set null",
	}),

	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
});

// ============================================================================
// Relations
// ============================================================================

export const storiesRelations = relations(stories, ({ many }) => ({
	scenes: many(scenes),
	images: many(images),
	audios: many(audios),
	videos: many(videos),
}));

export const scenesRelations = relations(scenes, ({ one }) => ({
	story: one(stories, { fields: [scenes.storyId], references: [stories.id] }),
	image: one(images, { fields: [scenes.imageId], references: [images.id] }),
	audio: one(audios, { fields: [scenes.audioId], references: [audios.id] }),
	video: one(videos, { fields: [scenes.videoId], references: [videos.id] }),
}));

export const imagesRelations = relations(images, ({ one }) => ({
	story: one(stories, { fields: [images.storyId], references: [stories.id] }),
	referenceImage: one(images, {
		fields: [images.referenceImageId],
		references: [images.id],
	}),
}));

export const audiosRelations = relations(audios, ({ one }) => ({
	story: one(stories, { fields: [audios.storyId], references: [stories.id] }),
}));

export const videosRelations = relations(videos, ({ one }) => ({
	story: one(stories, { fields: [videos.storyId], references: [stories.id] }),
	image: one(images, { fields: [videos.imageId], references: [images.id] }),
	audio: one(audios, { fields: [videos.audioId], references: [audios.id] }),
}));

// ============================================================================
// Type exports
// ============================================================================

export type Story = typeof stories.$inferSelect;
export type NewStory = typeof stories.$inferInsert;
export type Audio = typeof audios.$inferSelect;
export type NewAudio = typeof audios.$inferInsert;
export type Image = typeof images.$inferSelect;
export type NewImage = typeof images.$inferInsert;
export type Video = typeof videos.$inferSelect;
export type NewVideo = typeof videos.$inferInsert;
export type Scene = typeof scenes.$inferSelect;
export type NewScene = typeof scenes.$inferInsert;

// Media status type
export type MediaStatus = "ready" | "generating" | "completed";
export type ImageType = "scene" | "character" | "person1" | "person2";
export type StoryType = "aistory" | "podcast42" | "director-mode";
