import { Store } from "@tanstack/store";
import type { Scene, WordTimestamp } from "@/hooks/use-aistory-api";

// ============================================================================
// Error State Types
// ============================================================================

/**
 * 增強的錯誤狀態結構
 * 包含錯誤代碼、時間戳和重試計數
 */
export interface ErrorState {
	/** 錯誤訊息 */
	message: string;
	/** 錯誤代碼 (用於分類和處理) */
	code?: string;
	/** 錯誤發生時間 */
	timestamp: number;
	/** 重試次數 */
	retryCount: number;
	/** 是否可重試 */
	retryable?: boolean;
	/** 相關的操作類型 */
	operation?: "story" | "character" | "image" | "audio" | "video" | "export";
	/** 相關的資源 ID */
	resourceId?: string;
}

/**
 * 建立錯誤狀態
 */
export function createErrorState(
	message: string,
	options: Partial<Omit<ErrorState, "message" | "timestamp">> = {},
): ErrorState {
	return {
		message,
		timestamp: Date.now(),
		retryCount: 0,
		retryable: true,
		...options,
	};
}

/**
 * 增加錯誤的重試計數
 */
export function incrementRetryCount(
	error: ErrorState | null,
): ErrorState | null {
	if (!error) return null;
	return {
		...error,
		retryCount: error.retryCount + 1,
		timestamp: Date.now(),
	};
}

// Image engine options for generation (all via FAL AI)
export type ImageEngine = "flux-pro" | "gpt-image-1.5" | "nano-banana-pro" | "nano-banana";

// Image style options for prompt + image generation
export type ImageStyle =
	| "cinematic"
	| "comic"
	| "low-poly"
	| "japanese-anime"
	| "clay";

// Voice options for ElevenLabs narration
export type VoiceId =
	| "PIGsltMj3gFMR34aFDI3" // Jonathan
	| "Z3R5wn05IrDiVCyEkUrK" // Arabella
	| "n1PvBOwxb8X6m7tahp2h" // Michael
	| "ZF6FPAbjXT4488VcRRnw" // Amelia
	| "ICwKbPHDHAM3eal5tHEZ" // Tony
	| "cgLpYGyXZhkyalKZ0xeZ" // Knox
	| "YKrm0N1EAM9Bw27j8kuD"; // Leonidas

// Video engine options for FAL-AI
export type VideoEngine =
	| "kling-video"
	| "kling-video-v2.5-turbo"
	| "sora-2"
	| "ltx-2-19b"
	| "veo3.1"
	| "veo3.1-fast";

// LLM engine options for prompt generation
export type LLMEngine = "gpt-4.1" | "claude-opus-4-5" | "gemini-2.5-pro";

// Caption language options
export type CaptionLanguage = "en" | "zh-TW";

// Media status type (matches database enum)
export type MediaStatus = "ready" | "generating" | "completed";

// Extended scene state with UI-related fields
export interface SceneState extends Scene {
	// Database media IDs
	imageId?: string;
	audioId?: string;
	videoId?: string;
	// Supabase Storage URLs
	imageUrl?: string;
	audioUrl?: string;
	videoUrl?: string;
	// Database media status (for resuming generation monitoring)
	imageStatus?: MediaStatus;
	audioStatus?: MediaStatus;
	videoStatus?: MediaStatus;
	// Per-scene voice settings
	voiceId?: VoiceId;
	voiceSpeed?: number;
	// UI state
	isLoading?: boolean;
	audioDuration?: number;
	isGeneratingAudio?: boolean;
	// Word-level timestamps for synchronized caption display
	wordTimestamps?: WordTimestamp[];
	// Video generation fields
	videoDuration?: number;
	isGeneratingVideo?: boolean;
	videoError?: string | null;
}

// AI Story store state interface
export interface AIStoryState {
	// Script input
	script: string;

	// Database persistence state
	storyId: string | null; // Database story ID (set after prompts generated)
	storyTitle: string | null; // Story title (generated by LLM or set by user)
	sceneDbIds: Record<string, string>; // clientId -> dbId mapping

	// Character data
	characterPrompt: string | null;
	characterImageId: string | null; // Database image ID
	characterImageUrl: string | null; // Supabase Storage URL (used by all FAL engines)

	// Character generation state
	isGeneratingCharacter: boolean;

	// Scenes data
	scenes: SceneState[];

	// Prompt generation state
	isGeneratingPrompts: boolean;
	promptsGenerated: boolean;

	// Audio playback
	playingSceneId: string | null;

	// Error state (增強版，包含代碼、時間戳、重試計數)
	error: ErrorState | null;
	sceneError: ErrorState | null;

	// Export video state
	isExportingVideo: boolean;
	exportedVideoUrl: string | null;
	exportError: ErrorState | null;

	// Engine selections
	imageEngine: ImageEngine;
	videoEngine: VideoEngine;
	imageStyle: ImageStyle;
	llmEngine: LLMEngine;
	captionLanguage: CaptionLanguage;

	// Batch generation state
	isGeneratingAllImages: boolean;
	isGeneratingAllVideos: boolean;
	batchImageProgress: { current: number; total: number } | null;
	batchVideoProgress: { current: number; total: number } | null;
	batchCancelled: boolean;
}

// Initial state
const initialState: AIStoryState = {
	script: "",
	storyId: null,
	storyTitle: null,
	sceneDbIds: {},
	characterPrompt: null,
	characterImageId: null,
	characterImageUrl: null,
	isGeneratingCharacter: false,
	scenes: [],
	isGeneratingPrompts: false,
	promptsGenerated: false,
	playingSceneId: null,
	error: null,
	sceneError: null,
	isExportingVideo: false,
	exportedVideoUrl: null,
	exportError: null,
	imageEngine: "flux-pro",
	videoEngine: "kling-video",
	imageStyle: "cinematic",
	llmEngine: "gpt-4.1",
	captionLanguage: "en",
	isGeneratingAllImages: false,
	isGeneratingAllVideos: false,
	batchImageProgress: null,
	batchVideoProgress: null,
	batchCancelled: false,
};

// Create the store
export const aistoryStore = new Store<AIStoryState>(initialState);

// Action helpers
export const aistoryActions = {
	setScript: (script: string) => {
		aistoryStore.setState((state) => ({ ...state, script }));
	},

	// Database persistence actions
	setStoryId: (storyId: string | null) => {
		aistoryStore.setState((state) => ({ ...state, storyId }));
	},

	setStoryTitle: (storyTitle: string | null) => {
		aistoryStore.setState((state) => ({ ...state, storyTitle }));
	},

	setSceneDbIds: (sceneDbIds: Record<string, string>) => {
		aistoryStore.setState((state) => ({ ...state, sceneDbIds }));
	},

	// Get database scene ID from client scene ID
	getSceneDbId: (clientId: string): string | undefined => {
		return aistoryStore.state.sceneDbIds[clientId];
	},

	setCharacterPrompt: (characterPrompt: string) => {
		aistoryStore.setState((state) => ({ ...state, characterPrompt }));
	},

	setCharacterImageId: (characterImageId: string | null) => {
		aistoryStore.setState((state) => ({ ...state, characterImageId }));
	},

	setCharacterImageUrl: (characterImageUrl: string | null) => {
		aistoryStore.setState((state) => ({ ...state, characterImageUrl }));
	},

	setIsGeneratingCharacter: (isGeneratingCharacter: boolean) => {
		aistoryStore.setState((state) => ({ ...state, isGeneratingCharacter }));
	},

	setScenes: (scenes: SceneState[]) => {
		aistoryStore.setState((state) => ({ ...state, scenes }));
	},

	updateScene: (sceneId: string, updates: Partial<SceneState>) => {
		aistoryStore.setState((state) => ({
			...state,
			scenes: state.scenes.map((scene) =>
				scene.id === sceneId ? { ...scene, ...updates } : scene,
			),
		}));
	},

	// Add a new scene after the specified scene (or at the end if no sceneId provided)
	addScene: (afterSceneId?: string) => {
		aistoryStore.setState((state) => {
			const newScene: SceneState = {
				id: `scene-new-${Date.now()}`,
				title: "New Scene",
				prompt: "",
				video_prompt: "",
				isCharacter: true,
				caption: "",
			};
			if (!afterSceneId) {
				return { ...state, scenes: [...state.scenes, newScene] };
			}
			const index = state.scenes.findIndex((s) => s.id === afterSceneId);
			const newScenes = [...state.scenes];
			newScenes.splice(index + 1, 0, newScene);
			return { ...state, scenes: newScenes };
		});
	},

	// Delete a scene by ID
	deleteScene: (sceneId: string) => {
		aistoryStore.setState((state) => ({
			...state,
			scenes: state.scenes.filter((s) => s.id !== sceneId),
		}));
	},

	// Reorder scenes by moving from one index to another
	reorderScenes: (fromIndex: number, toIndex: number) => {
		aistoryStore.setState((state) => {
			const newScenes = [...state.scenes];
			const [moved] = newScenes.splice(fromIndex, 1);
			newScenes.splice(toIndex, 0, moved);
			return { ...state, scenes: newScenes };
		});
	},

	setIsGeneratingPrompts: (isGeneratingPrompts: boolean) => {
		aistoryStore.setState((state) => ({ ...state, isGeneratingPrompts }));
	},

	setPromptsGenerated: (promptsGenerated: boolean) => {
		aistoryStore.setState((state) => ({ ...state, promptsGenerated }));
	},

	setPlayingSceneId: (playingSceneId: string | null) => {
		aistoryStore.setState((state) => ({ ...state, playingSceneId }));
	},

	/**
	 * 設定錯誤狀態
	 * @param error - 錯誤訊息字串、ErrorState 物件，或 null 清除錯誤
	 * @param options - 額外選項 (當 error 為字串時使用)
	 */
	setError: (
		error: string | ErrorState | null,
		options?: Partial<Omit<ErrorState, "message" | "timestamp">>,
	) => {
		aistoryStore.setState((state) => ({
			...state,
			error:
				error === null
					? null
					: typeof error === "string"
						? createErrorState(error, options)
						: error,
		}));
	},

	/**
	 * 設定場景錯誤狀態
	 * @param sceneError - 錯誤訊息字串、ErrorState 物件，或 null 清除錯誤
	 * @param options - 額外選項 (當 error 為字串時使用)
	 */
	setSceneError: (
		sceneError: string | ErrorState | null,
		options?: Partial<Omit<ErrorState, "message" | "timestamp">>,
	) => {
		aistoryStore.setState((state) => ({
			...state,
			sceneError:
				sceneError === null
					? null
					: typeof sceneError === "string"
						? createErrorState(sceneError, options)
						: sceneError,
		}));
	},

	// Export video actions
	setIsExportingVideo: (isExportingVideo: boolean) => {
		aistoryStore.setState((state) => ({ ...state, isExportingVideo }));
	},

	setExportedVideoUrl: (exportedVideoUrl: string | null) => {
		aistoryStore.setState((state) => ({ ...state, exportedVideoUrl }));
	},

	setExportError: (
		exportError: string | ErrorState | null,
		options?: Partial<Omit<ErrorState, "message" | "timestamp">>,
	) => {
		aistoryStore.setState((state) => ({
			...state,
			exportError:
				exportError === null
					? null
					: typeof exportError === "string"
						? createErrorState(exportError, { operation: "export", ...options })
						: exportError,
		}));
	},

	// Engine selections
	setImageEngine: (imageEngine: ImageEngine) => {
		aistoryStore.setState((state) => ({ ...state, imageEngine }));
	},

	setVideoEngine: (videoEngine: VideoEngine) => {
		aistoryStore.setState((state) => ({ ...state, videoEngine }));
	},

	setImageStyle: (imageStyle: ImageStyle) => {
		aistoryStore.setState((state) => ({ ...state, imageStyle }));
	},

	setLLMEngine: (llmEngine: LLMEngine) => {
		aistoryStore.setState((state) => ({ ...state, llmEngine }));
	},

	setCaptionLanguage: (captionLanguage: CaptionLanguage) => {
		aistoryStore.setState((state) => ({ ...state, captionLanguage }));
	},

	// Batch generation actions
	setIsGeneratingAllImages: (isGeneratingAllImages: boolean) => {
		aistoryStore.setState((state) => ({ ...state, isGeneratingAllImages }));
	},

	setIsGeneratingAllVideos: (isGeneratingAllVideos: boolean) => {
		aistoryStore.setState((state) => ({ ...state, isGeneratingAllVideos }));
	},

	setBatchImageProgress: (
		batchImageProgress: { current: number; total: number } | null,
	) => {
		aistoryStore.setState((state) => ({ ...state, batchImageProgress }));
	},

	setBatchVideoProgress: (
		batchVideoProgress: { current: number; total: number } | null,
	) => {
		aistoryStore.setState((state) => ({ ...state, batchVideoProgress }));
	},

	setBatchCancelled: (batchCancelled: boolean) => {
		aistoryStore.setState((state) => ({ ...state, batchCancelled }));
	},

	cancelBatchGeneration: () => {
		aistoryStore.setState((state) => ({ ...state, batchCancelled: true }));
	},

	// Reset all state except script
	resetPrompts: () => {
		aistoryStore.setState((state) => ({
			...state,
			storyId: null,
			sceneDbIds: {},
			characterPrompt: null,
			characterImageId: null,
			characterImageUrl: null,
			scenes: [],
			promptsGenerated: false,
			error: null,
			sceneError: null,
			isExportingVideo: false,
			exportedVideoUrl: null,
			exportError: null,
			isGeneratingAllImages: false,
			isGeneratingAllVideos: false,
			batchImageProgress: null,
			batchVideoProgress: null,
			batchCancelled: false,
		}));
	},

	// Full reset
	reset: () => {
		aistoryStore.setState(() => initialState);
	},
};
