/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as Podcast42RouteImport } from './routes/podcast42'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AssetLibraryRouteImport } from './routes/asset-library'
import { Route as AistoryRouteImport } from './routes/aistory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Podcast42IndexRouteImport } from './routes/podcast42/index'
import { Route as DirectorModeIndexRouteImport } from './routes/director-mode/index'
import { Route as AistoryIndexRouteImport } from './routes/aistory/index'
import { Route as Podcast42ScenesRouteImport } from './routes/podcast42/scenes'
import { Route as Podcast42ExportRouteImport } from './routes/podcast42/export'
import { Route as DirectorModeSubtitlesRouteImport } from './routes/director-mode/subtitles'
import { Route as DirectorModeScenesRouteImport } from './routes/director-mode/scenes'
import { Route as DirectorModeExportRouteImport } from './routes/director-mode/export'
import { Route as ApiUserPreferencesRouteImport } from './routes/api/user-preferences'
import { Route as ApiUploadPodcast42CharacterRouteImport } from './routes/api/upload-podcast42-character'
import { Route as ApiUploadCharacterRouteImport } from './routes/api/upload-character'
import { Route as ApiUpdateStorySettingsRouteImport } from './routes/api/update-story-settings'
import { Route as ApiUpdateSoundEffectOffsetRouteImport } from './routes/api/update-sound-effect-offset'
import { Route as ApiUpdateSceneVoiceRouteImport } from './routes/api/update-scene-voice'
import { Route as ApiUpdateScenePromptRouteImport } from './routes/api/update-scene-prompt'
import { Route as ApiUpdateSceneEnginesRouteImport } from './routes/api/update-scene-engines'
import { Route as ApiUpdateSceneCaptionRouteImport } from './routes/api/update-scene-caption'
import { Route as ApiSubtitleSettingsRouteImport } from './routes/api/subtitle-settings'
import { Route as ApiStoryMetadataRouteImport } from './routes/api/story-metadata'
import { Route as ApiReorderScenesRouteImport } from './routes/api/reorder-scenes'
import { Route as ApiProcessImageRouteImport } from './routes/api/process-image'
import { Route as ApiPodcast42GenerateVideoRouteImport } from './routes/api/podcast42-generate-video'
import { Route as ApiPodcast42GeneratePromptsRouteImport } from './routes/api/podcast42-generate-prompts'
import { Route as ApiPodcast42ExportVideoRouteImport } from './routes/api/podcast42-export-video'
import { Route as ApiPodcast42DeleteSceneFilesRouteImport } from './routes/api/podcast42-delete-scene-files'
import { Route as ApiMergeSoundEffectRouteImport } from './routes/api/merge-sound-effect'
import { Route as ApiLinkSceneMediaRouteImport } from './routes/api/link-scene-media'
import { Route as ApiLinkCharacterRouteImport } from './routes/api/link-character'
import { Route as ApiGetMediaStatusRouteImport } from './routes/api/get-media-status'
import { Route as ApiGetJobStatusRouteImport } from './routes/api/get-job-status'
import { Route as ApiGenerateSoundEffectRouteImport } from './routes/api/generate-sound-effect'
import { Route as ApiGenerateSceneVideoRouteImport } from './routes/api/generate-scene-video'
import { Route as ApiGenerateSceneImageRouteImport } from './routes/api/generate-scene-image'
import { Route as ApiGenerateSceneAudioRouteImport } from './routes/api/generate-scene-audio'
import { Route as ApiGeneratePromptsRouteImport } from './routes/api/generate-prompts'
import { Route as ApiGenerateCharacterRouteImport } from './routes/api/generate-character'
import { Route as ApiExportVideoRouteImport } from './routes/api/export-video'
import { Route as ApiCronCleanupJobsRouteImport } from './routes/api/cron-cleanup-jobs'
import { Route as ApiAssistantConversationRouteImport } from './routes/api/assistant-conversation'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant-chat'
import { Route as ApiAssetLibraryRouteImport } from './routes/api/asset-library'
import { Route as AistorySubtitlesRouteImport } from './routes/aistory/subtitles'
import { Route as AistoryScenesRouteImport } from './routes/aistory/scenes'
import { Route as AistoryExportRouteImport } from './routes/aistory/export'
import { Route as ApiDirectorUpdateTitleRouteImport } from './routes/api/director/update-title'
import { Route as ApiDirectorCreateStoryRouteImport } from './routes/api/director/create-story'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const Podcast42Route = Podcast42RouteImport.update({
  id: '/podcast42',
  path: '/podcast42',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetLibraryRoute = AssetLibraryRouteImport.update({
  id: '/asset-library',
  path: '/asset-library',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryRoute = AistoryRouteImport.update({
  id: '/aistory',
  path: '/aistory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Podcast42IndexRoute = Podcast42IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Podcast42Route,
} as any)
const DirectorModeIndexRoute = DirectorModeIndexRouteImport.update({
  id: '/director-mode/',
  path: '/director-mode/',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryIndexRoute = AistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AistoryRoute,
} as any)
const Podcast42ScenesRoute = Podcast42ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => Podcast42Route,
} as any)
const Podcast42ExportRoute = Podcast42ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => Podcast42Route,
} as any)
const DirectorModeSubtitlesRoute = DirectorModeSubtitlesRouteImport.update({
  id: '/director-mode/subtitles',
  path: '/director-mode/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorModeScenesRoute = DirectorModeScenesRouteImport.update({
  id: '/director-mode/scenes',
  path: '/director-mode/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorModeExportRoute = DirectorModeExportRouteImport.update({
  id: '/director-mode/export',
  path: '/director-mode/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesRoute = ApiUserPreferencesRouteImport.update({
  id: '/api/user-preferences',
  path: '/api/user-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPodcast42CharacterRoute =
  ApiUploadPodcast42CharacterRouteImport.update({
    id: '/api/upload-podcast42-character',
    path: '/api/upload-podcast42-character',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadCharacterRoute = ApiUploadCharacterRouteImport.update({
  id: '/api/upload-character',
  path: '/api/upload-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateStorySettingsRoute = ApiUpdateStorySettingsRouteImport.update({
  id: '/api/update-story-settings',
  path: '/api/update-story-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateSoundEffectOffsetRoute =
  ApiUpdateSoundEffectOffsetRouteImport.update({
    id: '/api/update-sound-effect-offset',
    path: '/api/update-sound-effect-offset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUpdateSceneVoiceRoute = ApiUpdateSceneVoiceRouteImport.update({
  id: '/api/update-scene-voice',
  path: '/api/update-scene-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateScenePromptRoute = ApiUpdateScenePromptRouteImport.update({
  id: '/api/update-scene-prompt',
  path: '/api/update-scene-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateSceneEnginesRoute = ApiUpdateSceneEnginesRouteImport.update({
  id: '/api/update-scene-engines',
  path: '/api/update-scene-engines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateSceneCaptionRoute = ApiUpdateSceneCaptionRouteImport.update({
  id: '/api/update-scene-caption',
  path: '/api/update-scene-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitleSettingsRoute = ApiSubtitleSettingsRouteImport.update({
  id: '/api/subtitle-settings',
  path: '/api/subtitle-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryMetadataRoute = ApiStoryMetadataRouteImport.update({
  id: '/api/story-metadata',
  path: '/api/story-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReorderScenesRoute = ApiReorderScenesRouteImport.update({
  id: '/api/reorder-scenes',
  path: '/api/reorder-scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessImageRoute = ApiProcessImageRouteImport.update({
  id: '/api/process-image',
  path: '/api/process-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodcast42GenerateVideoRoute =
  ApiPodcast42GenerateVideoRouteImport.update({
    id: '/api/podcast42-generate-video',
    path: '/api/podcast42-generate-video',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPodcast42GeneratePromptsRoute =
  ApiPodcast42GeneratePromptsRouteImport.update({
    id: '/api/podcast42-generate-prompts',
    path: '/api/podcast42-generate-prompts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPodcast42ExportVideoRoute = ApiPodcast42ExportVideoRouteImport.update({
  id: '/api/podcast42-export-video',
  path: '/api/podcast42-export-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodcast42DeleteSceneFilesRoute =
  ApiPodcast42DeleteSceneFilesRouteImport.update({
    id: '/api/podcast42-delete-scene-files',
    path: '/api/podcast42-delete-scene-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMergeSoundEffectRoute = ApiMergeSoundEffectRouteImport.update({
  id: '/api/merge-sound-effect',
  path: '/api/merge-sound-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkSceneMediaRoute = ApiLinkSceneMediaRouteImport.update({
  id: '/api/link-scene-media',
  path: '/api/link-scene-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkCharacterRoute = ApiLinkCharacterRouteImport.update({
  id: '/api/link-character',
  path: '/api/link-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetMediaStatusRoute = ApiGetMediaStatusRouteImport.update({
  id: '/api/get-media-status',
  path: '/api/get-media-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetJobStatusRoute = ApiGetJobStatusRouteImport.update({
  id: '/api/get-job-status',
  path: '/api/get-job-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSoundEffectRoute = ApiGenerateSoundEffectRouteImport.update({
  id: '/api/generate-sound-effect',
  path: '/api/generate-sound-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneVideoRoute = ApiGenerateSceneVideoRouteImport.update({
  id: '/api/generate-scene-video',
  path: '/api/generate-scene-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneImageRoute = ApiGenerateSceneImageRouteImport.update({
  id: '/api/generate-scene-image',
  path: '/api/generate-scene-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneAudioRoute = ApiGenerateSceneAudioRouteImport.update({
  id: '/api/generate-scene-audio',
  path: '/api/generate-scene-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptsRoute = ApiGeneratePromptsRouteImport.update({
  id: '/api/generate-prompts',
  path: '/api/generate-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCharacterRoute = ApiGenerateCharacterRouteImport.update({
  id: '/api/generate-character',
  path: '/api/generate-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportVideoRoute = ApiExportVideoRouteImport.update({
  id: '/api/export-video',
  path: '/api/export-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupJobsRoute = ApiCronCleanupJobsRouteImport.update({
  id: '/api/cron-cleanup-jobs',
  path: '/api/cron-cleanup-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantConversationRoute =
  ApiAssistantConversationRouteImport.update({
    id: '/api/assistant-conversation',
    path: '/api/assistant-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant-chat',
  path: '/api/assistant-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetLibraryRoute = ApiAssetLibraryRouteImport.update({
  id: '/api/asset-library',
  path: '/api/asset-library',
  getParentRoute: () => rootRouteImport,
} as any)
const AistorySubtitlesRoute = AistorySubtitlesRouteImport.update({
  id: '/subtitles',
  path: '/subtitles',
  getParentRoute: () => AistoryRoute,
} as any)
const AistoryScenesRoute = AistoryScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AistoryRoute,
} as any)
const AistoryExportRoute = AistoryExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AistoryRoute,
} as any)
const ApiDirectorUpdateTitleRoute = ApiDirectorUpdateTitleRouteImport.update({
  id: '/api/director/update-title',
  path: '/api/director/update-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectorCreateStoryRoute = ApiDirectorCreateStoryRouteImport.update({
  id: '/api/director/create-story',
  path: '/api/director/create-story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/asset-library': typeof AssetLibraryRoute
  '/history': typeof HistoryRoute
  '/podcast42': typeof Podcast42RouteWithChildren
  '/user': typeof UserRoute
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/aistory/subtitles': typeof AistorySubtitlesRoute
  '/api/asset-library': typeof ApiAssetLibraryRoute
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/api/assistant-conversation': typeof ApiAssistantConversationRoute
  '/api/cron-cleanup-jobs': typeof ApiCronCleanupJobsRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/generate-sound-effect': typeof ApiGenerateSoundEffectRoute
  '/api/get-job-status': typeof ApiGetJobStatusRoute
  '/api/get-media-status': typeof ApiGetMediaStatusRoute
  '/api/link-character': typeof ApiLinkCharacterRoute
  '/api/link-scene-media': typeof ApiLinkSceneMediaRoute
  '/api/merge-sound-effect': typeof ApiMergeSoundEffectRoute
  '/api/podcast42-delete-scene-files': typeof ApiPodcast42DeleteSceneFilesRoute
  '/api/podcast42-export-video': typeof ApiPodcast42ExportVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/process-image': typeof ApiProcessImageRoute
  '/api/reorder-scenes': typeof ApiReorderScenesRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/subtitle-settings': typeof ApiSubtitleSettingsRoute
  '/api/update-scene-caption': typeof ApiUpdateSceneCaptionRoute
  '/api/update-scene-engines': typeof ApiUpdateSceneEnginesRoute
  '/api/update-scene-prompt': typeof ApiUpdateScenePromptRoute
  '/api/update-scene-voice': typeof ApiUpdateSceneVoiceRoute
  '/api/update-sound-effect-offset': typeof ApiUpdateSoundEffectOffsetRoute
  '/api/update-story-settings': typeof ApiUpdateStorySettingsRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/api/user-preferences': typeof ApiUserPreferencesRoute
  '/director-mode/export': typeof DirectorModeExportRoute
  '/director-mode/scenes': typeof DirectorModeScenesRoute
  '/director-mode/subtitles': typeof DirectorModeSubtitlesRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory/': typeof AistoryIndexRoute
  '/director-mode': typeof DirectorModeIndexRoute
  '/podcast42/': typeof Podcast42IndexRoute
  '/api/director/create-story': typeof ApiDirectorCreateStoryRoute
  '/api/director/update-title': typeof ApiDirectorUpdateTitleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-library': typeof AssetLibraryRoute
  '/history': typeof HistoryRoute
  '/user': typeof UserRoute
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/aistory/subtitles': typeof AistorySubtitlesRoute
  '/api/asset-library': typeof ApiAssetLibraryRoute
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/api/assistant-conversation': typeof ApiAssistantConversationRoute
  '/api/cron-cleanup-jobs': typeof ApiCronCleanupJobsRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/generate-sound-effect': typeof ApiGenerateSoundEffectRoute
  '/api/get-job-status': typeof ApiGetJobStatusRoute
  '/api/get-media-status': typeof ApiGetMediaStatusRoute
  '/api/link-character': typeof ApiLinkCharacterRoute
  '/api/link-scene-media': typeof ApiLinkSceneMediaRoute
  '/api/merge-sound-effect': typeof ApiMergeSoundEffectRoute
  '/api/podcast42-delete-scene-files': typeof ApiPodcast42DeleteSceneFilesRoute
  '/api/podcast42-export-video': typeof ApiPodcast42ExportVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/process-image': typeof ApiProcessImageRoute
  '/api/reorder-scenes': typeof ApiReorderScenesRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/subtitle-settings': typeof ApiSubtitleSettingsRoute
  '/api/update-scene-caption': typeof ApiUpdateSceneCaptionRoute
  '/api/update-scene-engines': typeof ApiUpdateSceneEnginesRoute
  '/api/update-scene-prompt': typeof ApiUpdateScenePromptRoute
  '/api/update-scene-voice': typeof ApiUpdateSceneVoiceRoute
  '/api/update-sound-effect-offset': typeof ApiUpdateSoundEffectOffsetRoute
  '/api/update-story-settings': typeof ApiUpdateStorySettingsRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/api/user-preferences': typeof ApiUserPreferencesRoute
  '/director-mode/export': typeof DirectorModeExportRoute
  '/director-mode/scenes': typeof DirectorModeScenesRoute
  '/director-mode/subtitles': typeof DirectorModeSubtitlesRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory': typeof AistoryIndexRoute
  '/director-mode': typeof DirectorModeIndexRoute
  '/podcast42': typeof Podcast42IndexRoute
  '/api/director/create-story': typeof ApiDirectorCreateStoryRoute
  '/api/director/update-title': typeof ApiDirectorUpdateTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/asset-library': typeof AssetLibraryRoute
  '/history': typeof HistoryRoute
  '/podcast42': typeof Podcast42RouteWithChildren
  '/user': typeof UserRoute
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/aistory/subtitles': typeof AistorySubtitlesRoute
  '/api/asset-library': typeof ApiAssetLibraryRoute
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/api/assistant-conversation': typeof ApiAssistantConversationRoute
  '/api/cron-cleanup-jobs': typeof ApiCronCleanupJobsRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/generate-sound-effect': typeof ApiGenerateSoundEffectRoute
  '/api/get-job-status': typeof ApiGetJobStatusRoute
  '/api/get-media-status': typeof ApiGetMediaStatusRoute
  '/api/link-character': typeof ApiLinkCharacterRoute
  '/api/link-scene-media': typeof ApiLinkSceneMediaRoute
  '/api/merge-sound-effect': typeof ApiMergeSoundEffectRoute
  '/api/podcast42-delete-scene-files': typeof ApiPodcast42DeleteSceneFilesRoute
  '/api/podcast42-export-video': typeof ApiPodcast42ExportVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/process-image': typeof ApiProcessImageRoute
  '/api/reorder-scenes': typeof ApiReorderScenesRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/subtitle-settings': typeof ApiSubtitleSettingsRoute
  '/api/update-scene-caption': typeof ApiUpdateSceneCaptionRoute
  '/api/update-scene-engines': typeof ApiUpdateSceneEnginesRoute
  '/api/update-scene-prompt': typeof ApiUpdateScenePromptRoute
  '/api/update-scene-voice': typeof ApiUpdateSceneVoiceRoute
  '/api/update-sound-effect-offset': typeof ApiUpdateSoundEffectOffsetRoute
  '/api/update-story-settings': typeof ApiUpdateStorySettingsRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/api/user-preferences': typeof ApiUserPreferencesRoute
  '/director-mode/export': typeof DirectorModeExportRoute
  '/director-mode/scenes': typeof DirectorModeScenesRoute
  '/director-mode/subtitles': typeof DirectorModeSubtitlesRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory/': typeof AistoryIndexRoute
  '/director-mode/': typeof DirectorModeIndexRoute
  '/podcast42/': typeof Podcast42IndexRoute
  '/api/director/create-story': typeof ApiDirectorCreateStoryRoute
  '/api/director/update-title': typeof ApiDirectorUpdateTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aistory'
    | '/asset-library'
    | '/history'
    | '/podcast42'
    | '/user'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/aistory/subtitles'
    | '/api/asset-library'
    | '/api/assistant-chat'
    | '/api/assistant-conversation'
    | '/api/cron-cleanup-jobs'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/generate-sound-effect'
    | '/api/get-job-status'
    | '/api/get-media-status'
    | '/api/link-character'
    | '/api/link-scene-media'
    | '/api/merge-sound-effect'
    | '/api/podcast42-delete-scene-files'
    | '/api/podcast42-export-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/process-image'
    | '/api/reorder-scenes'
    | '/api/story-metadata'
    | '/api/subtitle-settings'
    | '/api/update-scene-caption'
    | '/api/update-scene-engines'
    | '/api/update-scene-prompt'
    | '/api/update-scene-voice'
    | '/api/update-sound-effect-offset'
    | '/api/update-story-settings'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/api/user-preferences'
    | '/director-mode/export'
    | '/director-mode/scenes'
    | '/director-mode/subtitles'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory/'
    | '/director-mode'
    | '/podcast42/'
    | '/api/director/create-story'
    | '/api/director/update-title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-library'
    | '/history'
    | '/user'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/aistory/subtitles'
    | '/api/asset-library'
    | '/api/assistant-chat'
    | '/api/assistant-conversation'
    | '/api/cron-cleanup-jobs'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/generate-sound-effect'
    | '/api/get-job-status'
    | '/api/get-media-status'
    | '/api/link-character'
    | '/api/link-scene-media'
    | '/api/merge-sound-effect'
    | '/api/podcast42-delete-scene-files'
    | '/api/podcast42-export-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/process-image'
    | '/api/reorder-scenes'
    | '/api/story-metadata'
    | '/api/subtitle-settings'
    | '/api/update-scene-caption'
    | '/api/update-scene-engines'
    | '/api/update-scene-prompt'
    | '/api/update-scene-voice'
    | '/api/update-sound-effect-offset'
    | '/api/update-story-settings'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/api/user-preferences'
    | '/director-mode/export'
    | '/director-mode/scenes'
    | '/director-mode/subtitles'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory'
    | '/director-mode'
    | '/podcast42'
    | '/api/director/create-story'
    | '/api/director/update-title'
  id:
    | '__root__'
    | '/'
    | '/aistory'
    | '/asset-library'
    | '/history'
    | '/podcast42'
    | '/user'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/aistory/subtitles'
    | '/api/asset-library'
    | '/api/assistant-chat'
    | '/api/assistant-conversation'
    | '/api/cron-cleanup-jobs'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/generate-sound-effect'
    | '/api/get-job-status'
    | '/api/get-media-status'
    | '/api/link-character'
    | '/api/link-scene-media'
    | '/api/merge-sound-effect'
    | '/api/podcast42-delete-scene-files'
    | '/api/podcast42-export-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/process-image'
    | '/api/reorder-scenes'
    | '/api/story-metadata'
    | '/api/subtitle-settings'
    | '/api/update-scene-caption'
    | '/api/update-scene-engines'
    | '/api/update-scene-prompt'
    | '/api/update-scene-voice'
    | '/api/update-sound-effect-offset'
    | '/api/update-story-settings'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/api/user-preferences'
    | '/director-mode/export'
    | '/director-mode/scenes'
    | '/director-mode/subtitles'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory/'
    | '/director-mode/'
    | '/podcast42/'
    | '/api/director/create-story'
    | '/api/director/update-title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AistoryRoute: typeof AistoryRouteWithChildren
  AssetLibraryRoute: typeof AssetLibraryRoute
  HistoryRoute: typeof HistoryRoute
  Podcast42Route: typeof Podcast42RouteWithChildren
  UserRoute: typeof UserRoute
  ApiAssetLibraryRoute: typeof ApiAssetLibraryRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiAssistantConversationRoute: typeof ApiAssistantConversationRoute
  ApiCronCleanupJobsRoute: typeof ApiCronCleanupJobsRoute
  ApiExportVideoRoute: typeof ApiExportVideoRoute
  ApiGenerateCharacterRoute: typeof ApiGenerateCharacterRoute
  ApiGeneratePromptsRoute: typeof ApiGeneratePromptsRoute
  ApiGenerateSceneAudioRoute: typeof ApiGenerateSceneAudioRoute
  ApiGenerateSceneImageRoute: typeof ApiGenerateSceneImageRoute
  ApiGenerateSceneVideoRoute: typeof ApiGenerateSceneVideoRoute
  ApiGenerateSoundEffectRoute: typeof ApiGenerateSoundEffectRoute
  ApiGetJobStatusRoute: typeof ApiGetJobStatusRoute
  ApiGetMediaStatusRoute: typeof ApiGetMediaStatusRoute
  ApiLinkCharacterRoute: typeof ApiLinkCharacterRoute
  ApiLinkSceneMediaRoute: typeof ApiLinkSceneMediaRoute
  ApiMergeSoundEffectRoute: typeof ApiMergeSoundEffectRoute
  ApiPodcast42DeleteSceneFilesRoute: typeof ApiPodcast42DeleteSceneFilesRoute
  ApiPodcast42ExportVideoRoute: typeof ApiPodcast42ExportVideoRoute
  ApiPodcast42GeneratePromptsRoute: typeof ApiPodcast42GeneratePromptsRoute
  ApiPodcast42GenerateVideoRoute: typeof ApiPodcast42GenerateVideoRoute
  ApiProcessImageRoute: typeof ApiProcessImageRoute
  ApiReorderScenesRoute: typeof ApiReorderScenesRoute
  ApiStoryMetadataRoute: typeof ApiStoryMetadataRoute
  ApiSubtitleSettingsRoute: typeof ApiSubtitleSettingsRoute
  ApiUpdateSceneCaptionRoute: typeof ApiUpdateSceneCaptionRoute
  ApiUpdateSceneEnginesRoute: typeof ApiUpdateSceneEnginesRoute
  ApiUpdateScenePromptRoute: typeof ApiUpdateScenePromptRoute
  ApiUpdateSceneVoiceRoute: typeof ApiUpdateSceneVoiceRoute
  ApiUpdateSoundEffectOffsetRoute: typeof ApiUpdateSoundEffectOffsetRoute
  ApiUpdateStorySettingsRoute: typeof ApiUpdateStorySettingsRoute
  ApiUploadCharacterRoute: typeof ApiUploadCharacterRoute
  ApiUploadPodcast42CharacterRoute: typeof ApiUploadPodcast42CharacterRoute
  ApiUserPreferencesRoute: typeof ApiUserPreferencesRoute
  DirectorModeExportRoute: typeof DirectorModeExportRoute
  DirectorModeScenesRoute: typeof DirectorModeScenesRoute
  DirectorModeSubtitlesRoute: typeof DirectorModeSubtitlesRoute
  DirectorModeIndexRoute: typeof DirectorModeIndexRoute
  ApiDirectorCreateStoryRoute: typeof ApiDirectorCreateStoryRoute
  ApiDirectorUpdateTitleRoute: typeof ApiDirectorUpdateTitleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast42': {
      id: '/podcast42'
      path: '/podcast42'
      fullPath: '/podcast42'
      preLoaderRoute: typeof Podcast42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-library': {
      id: '/asset-library'
      path: '/asset-library'
      fullPath: '/asset-library'
      preLoaderRoute: typeof AssetLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory': {
      id: '/aistory'
      path: '/aistory'
      fullPath: '/aistory'
      preLoaderRoute: typeof AistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast42/': {
      id: '/podcast42/'
      path: '/'
      fullPath: '/podcast42/'
      preLoaderRoute: typeof Podcast42IndexRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/director-mode/': {
      id: '/director-mode/'
      path: '/director-mode'
      fullPath: '/director-mode'
      preLoaderRoute: typeof DirectorModeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory/': {
      id: '/aistory/'
      path: '/'
      fullPath: '/aistory/'
      preLoaderRoute: typeof AistoryIndexRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/podcast42/scenes': {
      id: '/podcast42/scenes'
      path: '/scenes'
      fullPath: '/podcast42/scenes'
      preLoaderRoute: typeof Podcast42ScenesRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/podcast42/export': {
      id: '/podcast42/export'
      path: '/export'
      fullPath: '/podcast42/export'
      preLoaderRoute: typeof Podcast42ExportRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/director-mode/subtitles': {
      id: '/director-mode/subtitles'
      path: '/director-mode/subtitles'
      fullPath: '/director-mode/subtitles'
      preLoaderRoute: typeof DirectorModeSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director-mode/scenes': {
      id: '/director-mode/scenes'
      path: '/director-mode/scenes'
      fullPath: '/director-mode/scenes'
      preLoaderRoute: typeof DirectorModeScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director-mode/export': {
      id: '/director-mode/export'
      path: '/director-mode/export'
      fullPath: '/director-mode/export'
      preLoaderRoute: typeof DirectorModeExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-preferences': {
      id: '/api/user-preferences'
      path: '/api/user-preferences'
      fullPath: '/api/user-preferences'
      preLoaderRoute: typeof ApiUserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-podcast42-character': {
      id: '/api/upload-podcast42-character'
      path: '/api/upload-podcast42-character'
      fullPath: '/api/upload-podcast42-character'
      preLoaderRoute: typeof ApiUploadPodcast42CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-character': {
      id: '/api/upload-character'
      path: '/api/upload-character'
      fullPath: '/api/upload-character'
      preLoaderRoute: typeof ApiUploadCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-story-settings': {
      id: '/api/update-story-settings'
      path: '/api/update-story-settings'
      fullPath: '/api/update-story-settings'
      preLoaderRoute: typeof ApiUpdateStorySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-sound-effect-offset': {
      id: '/api/update-sound-effect-offset'
      path: '/api/update-sound-effect-offset'
      fullPath: '/api/update-sound-effect-offset'
      preLoaderRoute: typeof ApiUpdateSoundEffectOffsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-scene-voice': {
      id: '/api/update-scene-voice'
      path: '/api/update-scene-voice'
      fullPath: '/api/update-scene-voice'
      preLoaderRoute: typeof ApiUpdateSceneVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-scene-prompt': {
      id: '/api/update-scene-prompt'
      path: '/api/update-scene-prompt'
      fullPath: '/api/update-scene-prompt'
      preLoaderRoute: typeof ApiUpdateScenePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-scene-engines': {
      id: '/api/update-scene-engines'
      path: '/api/update-scene-engines'
      fullPath: '/api/update-scene-engines'
      preLoaderRoute: typeof ApiUpdateSceneEnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-scene-caption': {
      id: '/api/update-scene-caption'
      path: '/api/update-scene-caption'
      fullPath: '/api/update-scene-caption'
      preLoaderRoute: typeof ApiUpdateSceneCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitle-settings': {
      id: '/api/subtitle-settings'
      path: '/api/subtitle-settings'
      fullPath: '/api/subtitle-settings'
      preLoaderRoute: typeof ApiSubtitleSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-metadata': {
      id: '/api/story-metadata'
      path: '/api/story-metadata'
      fullPath: '/api/story-metadata'
      preLoaderRoute: typeof ApiStoryMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reorder-scenes': {
      id: '/api/reorder-scenes'
      path: '/api/reorder-scenes'
      fullPath: '/api/reorder-scenes'
      preLoaderRoute: typeof ApiReorderScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-image': {
      id: '/api/process-image'
      path: '/api/process-image'
      fullPath: '/api/process-image'
      preLoaderRoute: typeof ApiProcessImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-generate-video': {
      id: '/api/podcast42-generate-video'
      path: '/api/podcast42-generate-video'
      fullPath: '/api/podcast42-generate-video'
      preLoaderRoute: typeof ApiPodcast42GenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-generate-prompts': {
      id: '/api/podcast42-generate-prompts'
      path: '/api/podcast42-generate-prompts'
      fullPath: '/api/podcast42-generate-prompts'
      preLoaderRoute: typeof ApiPodcast42GeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-export-video': {
      id: '/api/podcast42-export-video'
      path: '/api/podcast42-export-video'
      fullPath: '/api/podcast42-export-video'
      preLoaderRoute: typeof ApiPodcast42ExportVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-delete-scene-files': {
      id: '/api/podcast42-delete-scene-files'
      path: '/api/podcast42-delete-scene-files'
      fullPath: '/api/podcast42-delete-scene-files'
      preLoaderRoute: typeof ApiPodcast42DeleteSceneFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merge-sound-effect': {
      id: '/api/merge-sound-effect'
      path: '/api/merge-sound-effect'
      fullPath: '/api/merge-sound-effect'
      preLoaderRoute: typeof ApiMergeSoundEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-scene-media': {
      id: '/api/link-scene-media'
      path: '/api/link-scene-media'
      fullPath: '/api/link-scene-media'
      preLoaderRoute: typeof ApiLinkSceneMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-character': {
      id: '/api/link-character'
      path: '/api/link-character'
      fullPath: '/api/link-character'
      preLoaderRoute: typeof ApiLinkCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-media-status': {
      id: '/api/get-media-status'
      path: '/api/get-media-status'
      fullPath: '/api/get-media-status'
      preLoaderRoute: typeof ApiGetMediaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-job-status': {
      id: '/api/get-job-status'
      path: '/api/get-job-status'
      fullPath: '/api/get-job-status'
      preLoaderRoute: typeof ApiGetJobStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-sound-effect': {
      id: '/api/generate-sound-effect'
      path: '/api/generate-sound-effect'
      fullPath: '/api/generate-sound-effect'
      preLoaderRoute: typeof ApiGenerateSoundEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-video': {
      id: '/api/generate-scene-video'
      path: '/api/generate-scene-video'
      fullPath: '/api/generate-scene-video'
      preLoaderRoute: typeof ApiGenerateSceneVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-image': {
      id: '/api/generate-scene-image'
      path: '/api/generate-scene-image'
      fullPath: '/api/generate-scene-image'
      preLoaderRoute: typeof ApiGenerateSceneImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-audio': {
      id: '/api/generate-scene-audio'
      path: '/api/generate-scene-audio'
      fullPath: '/api/generate-scene-audio'
      preLoaderRoute: typeof ApiGenerateSceneAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompts': {
      id: '/api/generate-prompts'
      path: '/api/generate-prompts'
      fullPath: '/api/generate-prompts'
      preLoaderRoute: typeof ApiGeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-character': {
      id: '/api/generate-character'
      path: '/api/generate-character'
      fullPath: '/api/generate-character'
      preLoaderRoute: typeof ApiGenerateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-video': {
      id: '/api/export-video'
      path: '/api/export-video'
      fullPath: '/api/export-video'
      preLoaderRoute: typeof ApiExportVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron-cleanup-jobs': {
      id: '/api/cron-cleanup-jobs'
      path: '/api/cron-cleanup-jobs'
      fullPath: '/api/cron-cleanup-jobs'
      preLoaderRoute: typeof ApiCronCleanupJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-conversation': {
      id: '/api/assistant-conversation'
      path: '/api/assistant-conversation'
      fullPath: '/api/assistant-conversation'
      preLoaderRoute: typeof ApiAssistantConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-chat': {
      id: '/api/assistant-chat'
      path: '/api/assistant-chat'
      fullPath: '/api/assistant-chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset-library': {
      id: '/api/asset-library'
      path: '/api/asset-library'
      fullPath: '/api/asset-library'
      preLoaderRoute: typeof ApiAssetLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory/subtitles': {
      id: '/aistory/subtitles'
      path: '/subtitles'
      fullPath: '/aistory/subtitles'
      preLoaderRoute: typeof AistorySubtitlesRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/aistory/scenes': {
      id: '/aistory/scenes'
      path: '/scenes'
      fullPath: '/aistory/scenes'
      preLoaderRoute: typeof AistoryScenesRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/aistory/export': {
      id: '/aistory/export'
      path: '/export'
      fullPath: '/aistory/export'
      preLoaderRoute: typeof AistoryExportRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/api/director/update-title': {
      id: '/api/director/update-title'
      path: '/api/director/update-title'
      fullPath: '/api/director/update-title'
      preLoaderRoute: typeof ApiDirectorUpdateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director/create-story': {
      id: '/api/director/create-story'
      path: '/api/director/create-story'
      fullPath: '/api/director/create-story'
      preLoaderRoute: typeof ApiDirectorCreateStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AistoryRouteChildren {
  AistoryExportRoute: typeof AistoryExportRoute
  AistoryScenesRoute: typeof AistoryScenesRoute
  AistorySubtitlesRoute: typeof AistorySubtitlesRoute
  AistoryIndexRoute: typeof AistoryIndexRoute
}

const AistoryRouteChildren: AistoryRouteChildren = {
  AistoryExportRoute: AistoryExportRoute,
  AistoryScenesRoute: AistoryScenesRoute,
  AistorySubtitlesRoute: AistorySubtitlesRoute,
  AistoryIndexRoute: AistoryIndexRoute,
}

const AistoryRouteWithChildren =
  AistoryRoute._addFileChildren(AistoryRouteChildren)

interface Podcast42RouteChildren {
  Podcast42ExportRoute: typeof Podcast42ExportRoute
  Podcast42ScenesRoute: typeof Podcast42ScenesRoute
  Podcast42IndexRoute: typeof Podcast42IndexRoute
}

const Podcast42RouteChildren: Podcast42RouteChildren = {
  Podcast42ExportRoute: Podcast42ExportRoute,
  Podcast42ScenesRoute: Podcast42ScenesRoute,
  Podcast42IndexRoute: Podcast42IndexRoute,
}

const Podcast42RouteWithChildren = Podcast42Route._addFileChildren(
  Podcast42RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AistoryRoute: AistoryRouteWithChildren,
  AssetLibraryRoute: AssetLibraryRoute,
  HistoryRoute: HistoryRoute,
  Podcast42Route: Podcast42RouteWithChildren,
  UserRoute: UserRoute,
  ApiAssetLibraryRoute: ApiAssetLibraryRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiAssistantConversationRoute: ApiAssistantConversationRoute,
  ApiCronCleanupJobsRoute: ApiCronCleanupJobsRoute,
  ApiExportVideoRoute: ApiExportVideoRoute,
  ApiGenerateCharacterRoute: ApiGenerateCharacterRoute,
  ApiGeneratePromptsRoute: ApiGeneratePromptsRoute,
  ApiGenerateSceneAudioRoute: ApiGenerateSceneAudioRoute,
  ApiGenerateSceneImageRoute: ApiGenerateSceneImageRoute,
  ApiGenerateSceneVideoRoute: ApiGenerateSceneVideoRoute,
  ApiGenerateSoundEffectRoute: ApiGenerateSoundEffectRoute,
  ApiGetJobStatusRoute: ApiGetJobStatusRoute,
  ApiGetMediaStatusRoute: ApiGetMediaStatusRoute,
  ApiLinkCharacterRoute: ApiLinkCharacterRoute,
  ApiLinkSceneMediaRoute: ApiLinkSceneMediaRoute,
  ApiMergeSoundEffectRoute: ApiMergeSoundEffectRoute,
  ApiPodcast42DeleteSceneFilesRoute: ApiPodcast42DeleteSceneFilesRoute,
  ApiPodcast42ExportVideoRoute: ApiPodcast42ExportVideoRoute,
  ApiPodcast42GeneratePromptsRoute: ApiPodcast42GeneratePromptsRoute,
  ApiPodcast42GenerateVideoRoute: ApiPodcast42GenerateVideoRoute,
  ApiProcessImageRoute: ApiProcessImageRoute,
  ApiReorderScenesRoute: ApiReorderScenesRoute,
  ApiStoryMetadataRoute: ApiStoryMetadataRoute,
  ApiSubtitleSettingsRoute: ApiSubtitleSettingsRoute,
  ApiUpdateSceneCaptionRoute: ApiUpdateSceneCaptionRoute,
  ApiUpdateSceneEnginesRoute: ApiUpdateSceneEnginesRoute,
  ApiUpdateScenePromptRoute: ApiUpdateScenePromptRoute,
  ApiUpdateSceneVoiceRoute: ApiUpdateSceneVoiceRoute,
  ApiUpdateSoundEffectOffsetRoute: ApiUpdateSoundEffectOffsetRoute,
  ApiUpdateStorySettingsRoute: ApiUpdateStorySettingsRoute,
  ApiUploadCharacterRoute: ApiUploadCharacterRoute,
  ApiUploadPodcast42CharacterRoute: ApiUploadPodcast42CharacterRoute,
  ApiUserPreferencesRoute: ApiUserPreferencesRoute,
  DirectorModeExportRoute: DirectorModeExportRoute,
  DirectorModeScenesRoute: DirectorModeScenesRoute,
  DirectorModeSubtitlesRoute: DirectorModeSubtitlesRoute,
  DirectorModeIndexRoute: DirectorModeIndexRoute,
  ApiDirectorCreateStoryRoute: ApiDirectorCreateStoryRoute,
  ApiDirectorUpdateTitleRoute: ApiDirectorUpdateTitleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
