/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Podcast42RouteImport } from './routes/podcast42'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AistoryRouteImport } from './routes/aistory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Podcast42IndexRouteImport } from './routes/podcast42/index'
import { Route as AistoryIndexRouteImport } from './routes/aistory/index'
import { Route as Podcast42ScenesRouteImport } from './routes/podcast42/scenes'
import { Route as Podcast42ExportRouteImport } from './routes/podcast42/export'
import { Route as ApiUploadPodcast42CharacterRouteImport } from './routes/api/upload-podcast42-character'
import { Route as ApiUploadCharacterRouteImport } from './routes/api/upload-character'
import { Route as ApiStoryMetadataRouteImport } from './routes/api/story-metadata'
import { Route as ApiPodcast42GenerateVideoRouteImport } from './routes/api/podcast42-generate-video'
import { Route as ApiPodcast42GeneratePromptsRouteImport } from './routes/api/podcast42-generate-prompts'
import { Route as ApiGenerateSceneVideoRouteImport } from './routes/api/generate-scene-video'
import { Route as ApiGenerateSceneImageRouteImport } from './routes/api/generate-scene-image'
import { Route as ApiGenerateSceneAudioRouteImport } from './routes/api/generate-scene-audio'
import { Route as ApiGeneratePromptsRouteImport } from './routes/api/generate-prompts'
import { Route as ApiGenerateCharacterRouteImport } from './routes/api/generate-character'
import { Route as ApiExportVideoRouteImport } from './routes/api/export-video'
import { Route as AistoryScenesRouteImport } from './routes/aistory/scenes'
import { Route as AistoryExportRouteImport } from './routes/aistory/export'

const Podcast42Route = Podcast42RouteImport.update({
  id: '/podcast42',
  path: '/podcast42',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryRoute = AistoryRouteImport.update({
  id: '/aistory',
  path: '/aistory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Podcast42IndexRoute = Podcast42IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Podcast42Route,
} as any)
const AistoryIndexRoute = AistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AistoryRoute,
} as any)
const Podcast42ScenesRoute = Podcast42ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => Podcast42Route,
} as any)
const Podcast42ExportRoute = Podcast42ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => Podcast42Route,
} as any)
const ApiUploadPodcast42CharacterRoute =
  ApiUploadPodcast42CharacterRouteImport.update({
    id: '/api/upload-podcast42-character',
    path: '/api/upload-podcast42-character',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadCharacterRoute = ApiUploadCharacterRouteImport.update({
  id: '/api/upload-character',
  path: '/api/upload-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryMetadataRoute = ApiStoryMetadataRouteImport.update({
  id: '/api/story-metadata',
  path: '/api/story-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodcast42GenerateVideoRoute =
  ApiPodcast42GenerateVideoRouteImport.update({
    id: '/api/podcast42-generate-video',
    path: '/api/podcast42-generate-video',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPodcast42GeneratePromptsRoute =
  ApiPodcast42GeneratePromptsRouteImport.update({
    id: '/api/podcast42-generate-prompts',
    path: '/api/podcast42-generate-prompts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGenerateSceneVideoRoute = ApiGenerateSceneVideoRouteImport.update({
  id: '/api/generate-scene-video',
  path: '/api/generate-scene-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneImageRoute = ApiGenerateSceneImageRouteImport.update({
  id: '/api/generate-scene-image',
  path: '/api/generate-scene-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneAudioRoute = ApiGenerateSceneAudioRouteImport.update({
  id: '/api/generate-scene-audio',
  path: '/api/generate-scene-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptsRoute = ApiGeneratePromptsRouteImport.update({
  id: '/api/generate-prompts',
  path: '/api/generate-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCharacterRoute = ApiGenerateCharacterRouteImport.update({
  id: '/api/generate-character',
  path: '/api/generate-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportVideoRoute = ApiExportVideoRouteImport.update({
  id: '/api/export-video',
  path: '/api/export-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryScenesRoute = AistoryScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AistoryRoute,
} as any)
const AistoryExportRoute = AistoryExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/history': typeof HistoryRoute
  '/podcast42': typeof Podcast42RouteWithChildren
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory/': typeof AistoryIndexRoute
  '/podcast42/': typeof Podcast42IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory': typeof AistoryIndexRoute
  '/podcast42': typeof Podcast42IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/history': typeof HistoryRoute
  '/podcast42': typeof Podcast42RouteWithChildren
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/podcast42-generate-prompts': typeof ApiPodcast42GeneratePromptsRoute
  '/api/podcast42-generate-video': typeof ApiPodcast42GenerateVideoRoute
  '/api/story-metadata': typeof ApiStoryMetadataRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/api/upload-podcast42-character': typeof ApiUploadPodcast42CharacterRoute
  '/podcast42/export': typeof Podcast42ExportRoute
  '/podcast42/scenes': typeof Podcast42ScenesRoute
  '/aistory/': typeof AistoryIndexRoute
  '/podcast42/': typeof Podcast42IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aistory'
    | '/history'
    | '/podcast42'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/story-metadata'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory/'
    | '/podcast42/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/story-metadata'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory'
    | '/podcast42'
  id:
    | '__root__'
    | '/'
    | '/aistory'
    | '/history'
    | '/podcast42'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/podcast42-generate-prompts'
    | '/api/podcast42-generate-video'
    | '/api/story-metadata'
    | '/api/upload-character'
    | '/api/upload-podcast42-character'
    | '/podcast42/export'
    | '/podcast42/scenes'
    | '/aistory/'
    | '/podcast42/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AistoryRoute: typeof AistoryRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  Podcast42Route: typeof Podcast42RouteWithChildren
  ApiExportVideoRoute: typeof ApiExportVideoRoute
  ApiGenerateCharacterRoute: typeof ApiGenerateCharacterRoute
  ApiGeneratePromptsRoute: typeof ApiGeneratePromptsRoute
  ApiGenerateSceneAudioRoute: typeof ApiGenerateSceneAudioRoute
  ApiGenerateSceneImageRoute: typeof ApiGenerateSceneImageRoute
  ApiGenerateSceneVideoRoute: typeof ApiGenerateSceneVideoRoute
  ApiPodcast42GeneratePromptsRoute: typeof ApiPodcast42GeneratePromptsRoute
  ApiPodcast42GenerateVideoRoute: typeof ApiPodcast42GenerateVideoRoute
  ApiStoryMetadataRoute: typeof ApiStoryMetadataRoute
  ApiUploadCharacterRoute: typeof ApiUploadCharacterRoute
  ApiUploadPodcast42CharacterRoute: typeof ApiUploadPodcast42CharacterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podcast42': {
      id: '/podcast42'
      path: '/podcast42'
      fullPath: '/podcast42'
      preLoaderRoute: typeof Podcast42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory': {
      id: '/aistory'
      path: '/aistory'
      fullPath: '/aistory'
      preLoaderRoute: typeof AistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast42/': {
      id: '/podcast42/'
      path: '/'
      fullPath: '/podcast42/'
      preLoaderRoute: typeof Podcast42IndexRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/aistory/': {
      id: '/aistory/'
      path: '/'
      fullPath: '/aistory/'
      preLoaderRoute: typeof AistoryIndexRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/podcast42/scenes': {
      id: '/podcast42/scenes'
      path: '/scenes'
      fullPath: '/podcast42/scenes'
      preLoaderRoute: typeof Podcast42ScenesRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/podcast42/export': {
      id: '/podcast42/export'
      path: '/export'
      fullPath: '/podcast42/export'
      preLoaderRoute: typeof Podcast42ExportRouteImport
      parentRoute: typeof Podcast42Route
    }
    '/api/upload-podcast42-character': {
      id: '/api/upload-podcast42-character'
      path: '/api/upload-podcast42-character'
      fullPath: '/api/upload-podcast42-character'
      preLoaderRoute: typeof ApiUploadPodcast42CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-character': {
      id: '/api/upload-character'
      path: '/api/upload-character'
      fullPath: '/api/upload-character'
      preLoaderRoute: typeof ApiUploadCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-metadata': {
      id: '/api/story-metadata'
      path: '/api/story-metadata'
      fullPath: '/api/story-metadata'
      preLoaderRoute: typeof ApiStoryMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-generate-video': {
      id: '/api/podcast42-generate-video'
      path: '/api/podcast42-generate-video'
      fullPath: '/api/podcast42-generate-video'
      preLoaderRoute: typeof ApiPodcast42GenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcast42-generate-prompts': {
      id: '/api/podcast42-generate-prompts'
      path: '/api/podcast42-generate-prompts'
      fullPath: '/api/podcast42-generate-prompts'
      preLoaderRoute: typeof ApiPodcast42GeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-video': {
      id: '/api/generate-scene-video'
      path: '/api/generate-scene-video'
      fullPath: '/api/generate-scene-video'
      preLoaderRoute: typeof ApiGenerateSceneVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-image': {
      id: '/api/generate-scene-image'
      path: '/api/generate-scene-image'
      fullPath: '/api/generate-scene-image'
      preLoaderRoute: typeof ApiGenerateSceneImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-audio': {
      id: '/api/generate-scene-audio'
      path: '/api/generate-scene-audio'
      fullPath: '/api/generate-scene-audio'
      preLoaderRoute: typeof ApiGenerateSceneAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompts': {
      id: '/api/generate-prompts'
      path: '/api/generate-prompts'
      fullPath: '/api/generate-prompts'
      preLoaderRoute: typeof ApiGeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-character': {
      id: '/api/generate-character'
      path: '/api/generate-character'
      fullPath: '/api/generate-character'
      preLoaderRoute: typeof ApiGenerateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-video': {
      id: '/api/export-video'
      path: '/api/export-video'
      fullPath: '/api/export-video'
      preLoaderRoute: typeof ApiExportVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory/scenes': {
      id: '/aistory/scenes'
      path: '/scenes'
      fullPath: '/aistory/scenes'
      preLoaderRoute: typeof AistoryScenesRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/aistory/export': {
      id: '/aistory/export'
      path: '/export'
      fullPath: '/aistory/export'
      preLoaderRoute: typeof AistoryExportRouteImport
      parentRoute: typeof AistoryRoute
    }
  }
}

interface AistoryRouteChildren {
  AistoryExportRoute: typeof AistoryExportRoute
  AistoryScenesRoute: typeof AistoryScenesRoute
  AistoryIndexRoute: typeof AistoryIndexRoute
}

const AistoryRouteChildren: AistoryRouteChildren = {
  AistoryExportRoute: AistoryExportRoute,
  AistoryScenesRoute: AistoryScenesRoute,
  AistoryIndexRoute: AistoryIndexRoute,
}

const AistoryRouteWithChildren =
  AistoryRoute._addFileChildren(AistoryRouteChildren)

interface Podcast42RouteChildren {
  Podcast42ExportRoute: typeof Podcast42ExportRoute
  Podcast42ScenesRoute: typeof Podcast42ScenesRoute
  Podcast42IndexRoute: typeof Podcast42IndexRoute
}

const Podcast42RouteChildren: Podcast42RouteChildren = {
  Podcast42ExportRoute: Podcast42ExportRoute,
  Podcast42ScenesRoute: Podcast42ScenesRoute,
  Podcast42IndexRoute: Podcast42IndexRoute,
}

const Podcast42RouteWithChildren = Podcast42Route._addFileChildren(
  Podcast42RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AistoryRoute: AistoryRouteWithChildren,
  HistoryRoute: HistoryRoute,
  Podcast42Route: Podcast42RouteWithChildren,
  ApiExportVideoRoute: ApiExportVideoRoute,
  ApiGenerateCharacterRoute: ApiGenerateCharacterRoute,
  ApiGeneratePromptsRoute: ApiGeneratePromptsRoute,
  ApiGenerateSceneAudioRoute: ApiGenerateSceneAudioRoute,
  ApiGenerateSceneImageRoute: ApiGenerateSceneImageRoute,
  ApiGenerateSceneVideoRoute: ApiGenerateSceneVideoRoute,
  ApiPodcast42GeneratePromptsRoute: ApiPodcast42GeneratePromptsRoute,
  ApiPodcast42GenerateVideoRoute: ApiPodcast42GenerateVideoRoute,
  ApiStoryMetadataRoute: ApiStoryMetadataRoute,
  ApiUploadCharacterRoute: ApiUploadCharacterRoute,
  ApiUploadPodcast42CharacterRoute: ApiUploadPodcast42CharacterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
