/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AistoryRouteImport } from './routes/aistory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AistoryIndexRouteImport } from './routes/aistory/index'
import { Route as ApiUploadCharacterRouteImport } from './routes/api/upload-character'
import { Route as ApiGenerateSceneVideoRouteImport } from './routes/api/generate-scene-video'
import { Route as ApiGenerateSceneImageRouteImport } from './routes/api/generate-scene-image'
import { Route as ApiGenerateSceneAudioRouteImport } from './routes/api/generate-scene-audio'
import { Route as ApiGeneratePromptsRouteImport } from './routes/api/generate-prompts'
import { Route as ApiGenerateCharacterRouteImport } from './routes/api/generate-character'
import { Route as ApiExportVideoRouteImport } from './routes/api/export-video'
import { Route as AistoryScenesRouteImport } from './routes/aistory/scenes'
import { Route as AistoryExportRouteImport } from './routes/aistory/export'

const AistoryRoute = AistoryRouteImport.update({
  id: '/aistory',
  path: '/aistory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryIndexRoute = AistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AistoryRoute,
} as any)
const ApiUploadCharacterRoute = ApiUploadCharacterRouteImport.update({
  id: '/api/upload-character',
  path: '/api/upload-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneVideoRoute = ApiGenerateSceneVideoRouteImport.update({
  id: '/api/generate-scene-video',
  path: '/api/generate-scene-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneImageRoute = ApiGenerateSceneImageRouteImport.update({
  id: '/api/generate-scene-image',
  path: '/api/generate-scene-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSceneAudioRoute = ApiGenerateSceneAudioRouteImport.update({
  id: '/api/generate-scene-audio',
  path: '/api/generate-scene-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptsRoute = ApiGeneratePromptsRouteImport.update({
  id: '/api/generate-prompts',
  path: '/api/generate-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCharacterRoute = ApiGenerateCharacterRouteImport.update({
  id: '/api/generate-character',
  path: '/api/generate-character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportVideoRoute = ApiExportVideoRouteImport.update({
  id: '/api/export-video',
  path: '/api/export-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AistoryScenesRoute = AistoryScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AistoryRoute,
} as any)
const AistoryExportRoute = AistoryExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/aistory/': typeof AistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/aistory': typeof AistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aistory': typeof AistoryRouteWithChildren
  '/aistory/export': typeof AistoryExportRoute
  '/aistory/scenes': typeof AistoryScenesRoute
  '/api/export-video': typeof ApiExportVideoRoute
  '/api/generate-character': typeof ApiGenerateCharacterRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/generate-scene-audio': typeof ApiGenerateSceneAudioRoute
  '/api/generate-scene-image': typeof ApiGenerateSceneImageRoute
  '/api/generate-scene-video': typeof ApiGenerateSceneVideoRoute
  '/api/upload-character': typeof ApiUploadCharacterRoute
  '/aistory/': typeof AistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aistory'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/upload-character'
    | '/aistory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/upload-character'
    | '/aistory'
  id:
    | '__root__'
    | '/'
    | '/aistory'
    | '/aistory/export'
    | '/aistory/scenes'
    | '/api/export-video'
    | '/api/generate-character'
    | '/api/generate-prompts'
    | '/api/generate-scene-audio'
    | '/api/generate-scene-image'
    | '/api/generate-scene-video'
    | '/api/upload-character'
    | '/aistory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AistoryRoute: typeof AistoryRouteWithChildren
  ApiExportVideoRoute: typeof ApiExportVideoRoute
  ApiGenerateCharacterRoute: typeof ApiGenerateCharacterRoute
  ApiGeneratePromptsRoute: typeof ApiGeneratePromptsRoute
  ApiGenerateSceneAudioRoute: typeof ApiGenerateSceneAudioRoute
  ApiGenerateSceneImageRoute: typeof ApiGenerateSceneImageRoute
  ApiGenerateSceneVideoRoute: typeof ApiGenerateSceneVideoRoute
  ApiUploadCharacterRoute: typeof ApiUploadCharacterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aistory': {
      id: '/aistory'
      path: '/aistory'
      fullPath: '/aistory'
      preLoaderRoute: typeof AistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory/': {
      id: '/aistory/'
      path: '/'
      fullPath: '/aistory/'
      preLoaderRoute: typeof AistoryIndexRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/api/upload-character': {
      id: '/api/upload-character'
      path: '/api/upload-character'
      fullPath: '/api/upload-character'
      preLoaderRoute: typeof ApiUploadCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-video': {
      id: '/api/generate-scene-video'
      path: '/api/generate-scene-video'
      fullPath: '/api/generate-scene-video'
      preLoaderRoute: typeof ApiGenerateSceneVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-image': {
      id: '/api/generate-scene-image'
      path: '/api/generate-scene-image'
      fullPath: '/api/generate-scene-image'
      preLoaderRoute: typeof ApiGenerateSceneImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scene-audio': {
      id: '/api/generate-scene-audio'
      path: '/api/generate-scene-audio'
      fullPath: '/api/generate-scene-audio'
      preLoaderRoute: typeof ApiGenerateSceneAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompts': {
      id: '/api/generate-prompts'
      path: '/api/generate-prompts'
      fullPath: '/api/generate-prompts'
      preLoaderRoute: typeof ApiGeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-character': {
      id: '/api/generate-character'
      path: '/api/generate-character'
      fullPath: '/api/generate-character'
      preLoaderRoute: typeof ApiGenerateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-video': {
      id: '/api/export-video'
      path: '/api/export-video'
      fullPath: '/api/export-video'
      preLoaderRoute: typeof ApiExportVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aistory/scenes': {
      id: '/aistory/scenes'
      path: '/scenes'
      fullPath: '/aistory/scenes'
      preLoaderRoute: typeof AistoryScenesRouteImport
      parentRoute: typeof AistoryRoute
    }
    '/aistory/export': {
      id: '/aistory/export'
      path: '/export'
      fullPath: '/aistory/export'
      preLoaderRoute: typeof AistoryExportRouteImport
      parentRoute: typeof AistoryRoute
    }
  }
}

interface AistoryRouteChildren {
  AistoryExportRoute: typeof AistoryExportRoute
  AistoryScenesRoute: typeof AistoryScenesRoute
  AistoryIndexRoute: typeof AistoryIndexRoute
}

const AistoryRouteChildren: AistoryRouteChildren = {
  AistoryExportRoute: AistoryExportRoute,
  AistoryScenesRoute: AistoryScenesRoute,
  AistoryIndexRoute: AistoryIndexRoute,
}

const AistoryRouteWithChildren =
  AistoryRoute._addFileChildren(AistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AistoryRoute: AistoryRouteWithChildren,
  ApiExportVideoRoute: ApiExportVideoRoute,
  ApiGenerateCharacterRoute: ApiGenerateCharacterRoute,
  ApiGeneratePromptsRoute: ApiGeneratePromptsRoute,
  ApiGenerateSceneAudioRoute: ApiGenerateSceneAudioRoute,
  ApiGenerateSceneImageRoute: ApiGenerateSceneImageRoute,
  ApiGenerateSceneVideoRoute: ApiGenerateSceneVideoRoute,
  ApiUploadCharacterRoute: ApiUploadCharacterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
